[project]
name = "0921"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "BaekHyoYoung", email = "108615164+HyoYoung0829@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.13.5",
]

[project.scripts]
0921 = "0921:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
